const Produits = [
    {
    idproduit: 1,
    image: require("../assets/produit.png"),
    nomProduit: 'Portable HP',
    details: 'example de details',
    prix: 500.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:2,
    image: require("../assets/dell.png"),
    nomProduit: 'Portable Dell',
    details: 'example de details',
    prix: 750.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit: 3,
    image: require("../assets/acer.png"),
    nomProduit: 'Portable Acer',
    details: 'example de details',
    prix: 660.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:4,
    image: require("../assets/macbook.png"),
    nomProduit: 'Portable Macbook',
    details: 'example de details',
    prix: 1750.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit: 5,
    image: require("../assets/msi.png"),
    nomProduit: 'Portable MSI',
    details: 'example de details',
    prix: 2500.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:6,
    image: require("../assets/asus.png"),
    nomProduit: 'Portable Asus',
    details: 'example de details',
    prix: 950.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:7,
    image: require("../assets/dell.png"),
    nomProduit: 'Portable Asus',
    details: 'example de details',
    prix: 950.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:8,
    image: require("../assets/asus.png"),
    nomProduit: 'Portable Asus',
    details: 'example de details',
    prix: 950.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:9,
    image: require("../assets/macbook1.png"),
    nomProduit: 'Portable Asus',
    details: 'example de details',
    prix: 950.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
},
{
    idproduit:10,
    image: require("../assets/macbook.png"),
    nomProduit: 'Portable Asus',
    details: 'example de details',
    prix: 950.99,
    fournisseur: 'HP',
    idSousCategorie: 1,
}
]
export default Produits;